# Generated by Django 4.0 on 2021-12-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='characteristic',
            field=models.CharField(default='No', help_text='characteristic', max_length=200),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='unit',
            field=models.CharField(default='No', help_text='unit', max_length=10),
        ),
    ]
