# Generated by Django 4.0 on 2021-12-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0002_nomenclature_characteristic_nomenclature_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='barcode',
            field=models.CharField(help_text='Barcode', max_length=20),
        ),
    ]
