# Generated by Django 4.0 on 2021-12-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0003_alter_nomenclature_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='inv_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
