# Generated by Django 4.0 on 2021-12-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0004_alter_nomenclature_inv_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='inv_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
    ]
