# Generated by Django 4.0 on 2021-12-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0005_alter_nomenclature_inv_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoiled',
            name='content_type',
            field=models.CharField(blank=True, help_text='The MIMEType of th file', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='spoiled',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
