# Generated by Django 4.0 on 2021-12-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0006_spoiled_content_type_spoiled_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoiled',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
