# Generated by Django 4.0 on 2021-12-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('spoiled', '0007_spoiled_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoiled',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
