# Generated by Django 4.0 on 2021-12-24 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0008_spoiled_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoiled',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spoiled.place'),
        ),
        migrations.AddField(
            model_name='spoiled',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spoiled.sub'),
        ),
    ]
