# Generated by Django 4.0 on 2021-12-25 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0009_spoiled_place_spoiled_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoiled',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spoiled.employee'),
        ),
    ]
