# Generated by Django 4.0 on 2021-12-25 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0010_spoiled_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name group', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Shop must be greater than 1 character')])),
            ],
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoiled.group'),
        ),
    ]
