# Generated by Django 4.0 on 2021-12-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0012_barcode_alter_nomenclature_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='barcode',
            field=models.CharField(help_text='plu', max_length=20),
        ),
    ]
