# Generated by Django 4.0 on 2021-12-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0013_alter_nomenclature_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoiled',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='spoiled',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
