# Generated by Django 4.0 on 2022-01-02 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('spoiled', '0014_spoiled_created_at_spoiled_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spoiled',
            name='employee',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='spoiled.employee'),
        ),
        migrations.AlterField(
            model_name='spoiled',
            name='nomenclature',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='spoiled.nomenclature'),
        ),
        migrations.AlterField(
            model_name='spoiled',
            name='owner',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='spoiled',
            name='place',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='spoiled.place'),
        ),
        migrations.AlterField(
            model_name='spoiled',
            name='shop',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='spoiled.shop'),
        ),
        migrations.AlterField(
            model_name='spoiled',
            name='sub',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='spoiled.sub'),
        ),
    ]
