# Generated by Django 4.0 on 2022-01-02 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0015_alter_spoiled_employee_alter_spoiled_nomenclature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spoiled',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spoiled.place'),
        ),
        migrations.AlterField(
            model_name='spoiled',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spoiled.sub'),
        ),
    ]
