# Generated by Django 4.0 on 2022-01-02 08:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0016_alter_spoiled_place_alter_spoiled_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoiled',
            name='number_photo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spoiled',
            name='comment',
            field=models.CharField(help_text='Что случилось', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Employee must be greater than 1 character')]),
        ),
        migrations.AlterField(
            model_name='spoiled',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoiled.shop'),
        ),
    ]
