# Generated by Django 4.0 on 2022-01-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0017_spoiled_number_photo_alter_spoiled_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoiled',
            name='name_photo',
            field=models.CharField(blank=True, help_text='Name foto', max_length=256, null=True),
        ),
    ]
