# Generated by Django 4.0 on 2022-01-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0022_delete_barcode_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spoiled',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
