# Generated by Django 4.0 on 2022-01-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('spoiled', '0023_alter_spoiled_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spoiled',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='spoiled',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='spoiled',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='spoiled',
            name='description_comment',
            field=models.TextField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spoiled',
            name='discount_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
