# Generated by Django 4.0 on 2022-01-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoiled', '0024_remove_spoiled_comment_remove_spoiled_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spoiled',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='spoiled',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
